// data.js
export const restaurantData = [
  {
    id: 1,
    name: "Foodworld",
    image: "/assets/images/image1.svg",
    discount: "20% off",
    isFast: true,
    rating: 46,
    openStatus: "Opens tomorrow",
  },
  {
    id: 2,
    name: "Pizzahub",
    image: "/assets/images/image2.svg",
    discount: "15% off",
    isFast: true,
    rating: 40,
    openStatus: "Opens tomorrow",
  },
  {
    id: 3,
    name: "Pizzahub",
    image: "/assets/images/image2.svg",
    discount: "15% off",
    isFast: true,
    rating: 40,
    openStatus: "Opens tomorrow",
  },
  {
    id: 4,
    name: "Pizzahub",
    image: "/assets/images/image2.svg",
    discount: "15% off",
    isFast: true,
    rating: 40,
    openStatus: "Opens tomorrow",
  },
  {
    id: 5,
    name: "Pizzahub",
    image: "/assets/images/image2.svg",
    discount: "15% off",
    isFast: true,
    rating: 40,
    openStatus: "Opens tomorrow",
  },
  {
    id: 6,
    name: "Pizzahub",
    image: "/assets/images/image2.svg",
    discount: "15% off",
    isFast: true,
    rating: 40,
    openStatus: "Opens tomorrow",
  },
  {
    id: 7,
    name: "Pizzahub",
    image: "/assets/images/image2.svg",
    discount: "15% off",
    isFast: true,
    rating: 40,
    openStatus: "Opens tomorrow",
  },
  {
    id: 8,
    name: "Pizzahub",
    image: "/assets/images/image2.svg",
    discount: "15% off",
    isFast: true,
    rating: 40,
    openStatus: "Opens tomorrow",
  },
];
